// CONNECT
export const CONNECT_REQUESTED = 'CONNECT_REQUESTED';
export const CONNECT_REFUSED = 'CONNECT_REFUSED';
export const CONNECTED = 'CONNECTED';

// DISCONNECT
export const DISCONNECT_REQUESTED = 'DISCONNECT_REQUESTED';

// MESSAGE
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
